apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: podinfo-update
  namespace: default
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: podinfo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
      signingKey:
        secretRef:
          name: my-git-auth
    push:
      branch: main
  update:
    path: ./infra
    strategy: Setters
