apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/beffaCo/fluxcd-gitops-application
  ref:
    branch: main
  secretRef:
    name: my-git-auth
